namespace StocksPlatform.Services.Analysis;

/// <summary>
/// Bilingual (English + Norwegian) financial sentiment lexicon.
/// Scores are in the range [-1.0, +1.0]: positive = bullish / good news,
/// negative = bearish / bad news.
///
/// Words NOT in this dictionary are silently skipped by
/// <see cref="PublicSentimentAnalyzer"/> and do not count toward
/// <c>WordsAnalyzed</c>.
/// </summary>
public static class FinancialWordScores
{
    public static readonly IReadOnlyDictionary<string, double> Scores =
        new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase)
        {
            // ── Strong positive ──────────────────────────────────────────────
            ["outstanding"]      =  0.9,
            ["exceptional"]      =  0.9,
            ["breakthrough"]     =  0.9,
            ["phenomenal"]       =  0.8,
            ["remarkable"]       =  0.7,
            ["surpassed"]        =  0.8,
            ["surpass"]          =  0.8,
            ["exceeded"]         =  0.8,
            ["exceed"]           =  0.7,
            ["exceeds"]          =  0.7,
            ["best"]             =  0.7,
            ["record"]           =  0.6,
            ["surge"]            =  0.6,
            ["surged"]           =  0.6,
            ["surging"]          =  0.6,

            // ── Positive ─────────────────────────────────────────────────────
            ["profitable"]       =  0.7,
            ["profitability"]    =  0.7,
            ["profit"]           =  0.6,
            ["profits"]          =  0.6,
            ["outperform"]       =  0.7,
            ["outperformed"]     =  0.7,
            ["outperforming"]    =  0.7,
            ["outperformance"]   =  0.7,
            ["success"]          =  0.7,
            ["successful"]       =  0.7,
            ["succeed"]          =  0.6,
            ["optimistic"]       =  0.6,
            ["optimism"]         =  0.6,
            ["beat"]             =  0.6,
            ["beats"]            =  0.6,
            ["dividend"]         =  0.6,
            ["dividends"]        =  0.6,
            ["achievement"]      =  0.6,
            ["growth"]           =  0.6,
            ["grow"]             =  0.5,
            ["growing"]          =  0.5,
            ["grown"]            =  0.5,
            ["grew"]             =  0.5,
            ["strong"]           =  0.5,
            ["stronger"]         =  0.5,
            ["strongest"]        =  0.6,
            ["strength"]         =  0.5,
            ["gains"]            =  0.5,
            ["gain"]             =  0.5,
            ["gained"]           =  0.5,
            ["expansion"]        =  0.5,
            ["expand"]           =  0.5,
            ["expanding"]        =  0.5,
            ["expanded"]         =  0.5,
            ["recovery"]         =  0.5,
            ["recover"]          =  0.5,
            ["recovering"]       =  0.5,
            ["win"]              =  0.5,
            ["wins"]             =  0.5,
            ["won"]              =  0.5,
            ["positive"]         =  0.5,
            ["positively"]       =  0.5,
            ["robust"]           =  0.5,
            ["confident"]        =  0.5,
            ["confidence"]       =  0.5,
            ["favorable"]        =  0.5,
            ["favourable"]       =  0.5,
            ["milestone"]        =  0.5,
            ["achieved"]         =  0.5,
            ["achieve"]          =  0.5,
            ["innovative"]       =  0.5,
            ["leading"]          =  0.4,
            ["leader"]           =  0.4,
            ["top"]              =  0.4,

            // ── Mild positive ────────────────────────────────────────────────
            ["increase"]         =  0.4,
            ["increased"]        =  0.4,
            ["increasing"]       =  0.4,
            ["improve"]          =  0.5,
            ["improved"]         =  0.5,
            ["improvement"]      =  0.5,
            ["improving"]        =  0.5,
            ["rise"]             =  0.4,
            ["risen"]            =  0.4,
            ["rises"]            =  0.4,
            ["rising"]           =  0.4,
            ["rose"]             =  0.4,
            ["advance"]          =  0.4,
            ["advanced"]         =  0.4,
            ["advancing"]        =  0.4,
            ["solid"]            =  0.4,
            ["innovation"]       =  0.4,
            ["efficient"]        =  0.4,
            ["efficiency"]       =  0.4,
            ["launch"]           =  0.4,
            ["launched"]         =  0.4,
            ["agreement"]        =  0.4,
            ["approved"]         =  0.4,
            ["upgrade"]          =  0.5,
            ["upgraded"]         =  0.5,
            ["accelerate"]       =  0.4,
            ["acceleration"]     =  0.4,
            ["award"]            =  0.5,
            ["awarded"]          =  0.5,
            ["partnership"]      =  0.4,
            ["better"]           =  0.4,
            ["highest"]          =  0.4,
            ["sustainable"]      =  0.4,
            ["sustainability"]   =  0.4,
            ["opportunity"]      =  0.5,
            ["earnings"]         =  0.4,
            ["revenue"]          =  0.3,
            ["revenues"]         =  0.3,
            ["contract"]         =  0.3,
            ["acquisition"]      =  0.3,

            // ── Mild negative ────────────────────────────────────────────────
            ["risk"]             = -0.3,
            ["risks"]            = -0.3,
            ["risky"]            = -0.4,
            ["concern"]          = -0.4,
            ["concerns"]         = -0.4,
            ["concerning"]       = -0.4,
            ["challenge"]        = -0.3,
            ["challenges"]       = -0.3,
            ["challenging"]      = -0.3,
            ["uncertain"]        = -0.4,
            ["uncertainty"]      = -0.4,
            ["uncertainties"]    = -0.4,
            ["decrease"]         = -0.4,
            ["decreased"]        = -0.4,
            ["decreasing"]       = -0.4,
            ["reduce"]           = -0.3,
            ["reduced"]          = -0.3,
            ["reduction"]        = -0.3,
            ["pressure"]         = -0.3,
            ["pressures"]        = -0.3,
            ["volatile"]         = -0.3,
            ["volatility"]       = -0.3,
            ["delay"]            = -0.4,
            ["delayed"]          = -0.4,
            ["delays"]           = -0.4,
            ["cut"]              = -0.4,
            ["cuts"]             = -0.4,
            ["cutting"]          = -0.4,
            ["debt"]             = -0.3,
            ["debts"]            = -0.3,
            ["inflation"]        = -0.3,
            ["headwind"]         = -0.4,
            ["headwinds"]        = -0.4,
            ["below"]            = -0.3,
            ["lower"]            = -0.3,
            ["lowest"]           = -0.4,
            ["restructure"]      = -0.4,
            ["restructured"]     = -0.4,
            ["restructuring"]    = -0.4,
            ["adverse"]          = -0.4,
            ["adversely"]        = -0.4,
            ["impacted"]         = -0.2,
            ["deteriorate"]      = -0.5,
            ["deteriorated"]     = -0.5,
            ["deteriorating"]    = -0.5,
            ["deterioration"]    = -0.5,

            // ── Negative ─────────────────────────────────────────────────────
            ["loss"]             = -0.6,
            ["losses"]           = -0.7,
            ["decline"]          = -0.5,
            ["declined"]         = -0.5,
            ["declines"]         = -0.5,
            ["declining"]        = -0.5,
            ["weak"]             = -0.5,
            ["weaker"]           = -0.5,
            ["weakest"]          = -0.6,
            ["weakness"]         = -0.5,
            ["weakened"]         = -0.5,
            ["weakening"]        = -0.5,
            ["fall"]             = -0.4,
            ["falls"]            = -0.4,
            ["fell"]             = -0.4,
            ["fallen"]           = -0.4,
            ["falling"]          = -0.4,
            ["drop"]             = -0.4,
            ["drops"]            = -0.4,
            ["dropped"]          = -0.4,
            ["dropping"]         = -0.4,
            ["miss"]             = -0.6,
            ["missed"]           = -0.6,
            ["misses"]           = -0.6,
            ["underperform"]     = -0.7,
            ["underperformed"]   = -0.7,
            ["underperforming"]  = -0.7,
            ["problem"]          = -0.5,
            ["problems"]         = -0.5,
            ["warning"]          = -0.5,
            ["warnings"]         = -0.5,
            ["layoff"]           = -0.6,
            ["layoffs"]          = -0.6,
            ["suspend"]          = -0.6,
            ["suspended"]        = -0.6,
            ["suspension"]       = -0.6,
            ["downgrade"]        = -0.6,
            ["downgraded"]       = -0.6,
            ["downgrades"]       = -0.6,
            ["disappointing"]    = -0.6,
            ["disappoint"]       = -0.6,
            ["disappointed"]     = -0.6,
            ["disappointment"]   = -0.6,
            ["bearish"]          = -0.6,
            ["negative"]         = -0.5,
            ["negatively"]       = -0.5,
            ["struggle"]         = -0.5,
            ["struggles"]        = -0.5,
            ["struggling"]       = -0.5,
            ["troubled"]         = -0.5,
            ["shortage"]         = -0.4,
            ["shortages"]        = -0.4,
            ["recession"]        = -0.7,
            ["dispute"]          = -0.4,
            ["disputes"]         = -0.4,
            ["controversy"]      = -0.5,
            ["controversial"]    = -0.5,
            ["investigation"]    = -0.5,
            ["investigated"]     = -0.5,
            ["investigating"]    = -0.5,
            ["penalty"]          = -0.5,
            ["penalties"]        = -0.5,
            ["lawsuit"]          = -0.6,
            ["lawsuits"]         = -0.6,
            ["fined"]            = -0.5,
            ["halt"]             = -0.5,
            ["halted"]           = -0.5,
            ["halts"]            = -0.5,
            ["accident"]         = -0.5,
            ["accidents"]        = -0.5,
            ["spill"]            = -0.6,
            ["leak"]             = -0.4,
            ["hurt"]             = -0.4,
            ["damage"]           = -0.5,
            ["damaged"]          = -0.5,
            ["worse"]            = -0.5,
            ["worst"]            = -0.6,

            // ── Strong negative ──────────────────────────────────────────────
            ["crisis"]           = -0.8,
            ["crises"]           = -0.8,
            ["fail"]             = -0.7,
            ["failed"]           = -0.7,
            ["failing"]          = -0.7,
            ["failure"]          = -0.7,
            ["failures"]         = -0.7,
            ["default"]          = -0.8,
            ["defaulted"]        = -0.8,
            ["bankruptcy"]       = -0.9,
            ["bankrupt"]         = -0.9,
            ["scandal"]          = -0.8,
            ["fraud"]            = -0.9,
            ["collapse"]         = -0.9,

            // ── Norwegian – positive ─────────────────────────────────────────
            ["vekst"]            =  0.6,   // growth
            ["økning"]           =  0.4,   // increase
            ["overskudd"]        =  0.6,   // surplus / profit
            ["positiv"]          =  0.5,   // positive
            ["sterk"]            =  0.5,   // strong
            ["sterkt"]           =  0.5,   // strongly
            ["bra"]              =  0.4,   // good / well
            ["god"]              =  0.4,   // good
            ["utbytte"]          =  0.6,   // dividend
            ["gevinst"]          =  0.5,   // gain / profit
            ["suksess"]          =  0.6,   // success
            ["rekord"]           =  0.6,   // record
            ["øker"]             =  0.4,   // increases
            ["økt"]              =  0.4,   // increased
            ["bedre"]            =  0.4,   // better
            ["forbedring"]       =  0.5,   // improvement
            ["tilfreds"]         =  0.5,   // satisfied
            ["fornøyd"]          =  0.5,   // satisfied / pleased
            ["fremgang"]         =  0.5,   // advancement / progress
            ["vinner"]           =  0.5,   // winner
            ["seier"]            =  0.6,   // victory
            ["stigning"]         =  0.4,   // rise / increase
            ["oppgang"]          =  0.4,   // upturn
            ["mulighet"]         =  0.4,   // opportunity

            // ── Norwegian – negative ─────────────────────────────────────────
            ["tap"]              = -0.6,   // loss
            ["nedgang"]          = -0.5,   // decline / decrease
            ["svak"]             = -0.5,   // weak
            ["bekymring"]        = -0.4,   // concern
            ["risiko"]           = -0.3,   // risk
            ["krise"]            = -0.8,   // crisis
            ["konkurs"]          = -0.9,   // bankruptcy
            ["nedskrivning"]     = -0.6,   // write-down
            ["faller"]           = -0.4,   // falls
            ["fallende"]         = -0.4,   // falling
            ["reduksjon"]        = -0.3,   // reduction
            ["kutt"]             = -0.4,   // cut
            ["varsel"]           = -0.4,   // warning / notice
            ["skuffende"]        = -0.5,   // disappointing
            ["svekket"]          = -0.4,   // weakened
            ["oppsigelse"]       = -0.5,   // dismissal / layoff
            ["oppsigelser"]      = -0.5,   // dismissals / layoffs
            ["negativ"]          = -0.5,   // negative
            ["lav"]              = -0.3,   // low
            ["lavt"]             = -0.3,   // low
            ["gransking"]        = -0.5,   // investigation
            ["uro"]              = -0.4,   // unrest / trouble
            ["usikkerhet"]       = -0.4,   // uncertainty
            ["nedskjæring"]      = -0.5,   // cutback
            ["utfordring"]       = -0.3,   // challenge
        };
}
