using Microsoft.EntityFrameworkCore;
using StocksPlatform.Data;
using StocksPlatform.Models;

namespace StocksPlatform.Services.Seeding;

/// <summary>
/// Seeds the S&amp;P 500 index portfolio with fixed market-cap weights.
/// Only components whose ticker already exists in the database are included;
/// missing tickers are silently skipped and the remaining weights are
/// renormalised so fractions still sum to 1.
/// </summary>
public static class SpFiveHundredSeeder
{
    /// <summary>S&amp;P 500 components: (Name, Symbol, Weight%).</summary>
    private static readonly (string Name, string Symbol, double Weight)[] Components =
    [
        ("Nvidia", "NVDA", 7.12),
        ("Apple Inc.", "AAPL", 6.18),
        ("Microsoft", "MSFT", 4.81),
        ("Amazon", "AMZN", 3.74),
        ("Alphabet Inc. (Class A)", "GOOGL", 3.20),
        ("Alphabet Inc. (Class C)", "GOOG", 2.96),
        ("Meta Platforms", "META", 2.55),
        ("Broadcom", "AVGO", 2.50),
        ("Tesla, Inc.", "TSLA", 2.34),
        ("Berkshire Hathaway", "BRK.B", 1.76),
        ("Walmart", "WMT", 1.61),
        ("Lilly (Eli)", "LLY", 1.37),
        ("JPMorgan Chase", "JPM", 1.31),
        ("ExxonMobil", "XOM", 1.13),
        ("Visa Inc.", "V", 0.98),
        ("Johnson & Johnson", "JNJ", 0.96),
        ("Micron Technology", "MU", 0.81),
        ("Mastercard", "MA", 0.75),
        ("Costco", "COST", 0.73),
        ("Oracle Corporation", "ORCL", 0.73),
        ("Chevron Corporation", "CVX", 0.68),
        ("Netflix", "NFLX", 0.66),
        ("AbbVie", "ABBV", 0.62),
        ("Palantir Technologies", "PLTR", 0.61),
        ("Bank of America", "BAC", 0.57),
        ("Procter & Gamble", "PG", 0.57),
        ("Advanced Micro Devices", "AMD", 0.56),
        ("Coca-Cola Company", "KO", 0.55),
        ("Home Depot", "HD", 0.54),
        ("Caterpillar Inc.", "CAT", 0.54),
        ("Cisco", "CSCO", 0.52),
        ("GE Aerospace", "GE", 0.51),
        ("Lam Research", "LRCX", 0.48),
        ("Applied Materials", "AMAT", 0.48),
        ("Merck & Co.", "MRK", 0.48),
        ("RTX Corporation", "RTX", 0.45),
        ("Morgan Stanley", "MS", 0.44),
        ("Philip Morris International", "PM", 0.43),
        ("UnitedHealth Group", "UNH", 0.42),
        ("Goldman Sachs", "GS", 0.41),
        ("Wells Fargo", "WFC", 0.41),
        ("T-Mobile US", "TMUS", 0.39),
        ("GE Vernova", "GEV", 0.39),
        ("IBM", "IBM", 0.39),
        ("Linde plc", "LIN", 0.38),
        ("McDonald's", "MCD", 0.37),
        ("Intel", "INTC", 0.37),
        ("Verizon", "VZ", 0.36),
        ("PepsiCo", "PEP", 0.35),
        ("American Express", "AXP", 0.34),
        ("AT&T", "T", 0.34),
        ("KLA Corporation", "KLAC", 0.33),
        ("Citigroup", "C", 0.33),
        ("Amgen", "AMGN", 0.32),
        ("NextEra Energy", "NEE", 0.32),
        ("Abbott Laboratories", "ABT", 0.31),
        ("Salesforce", "CRM", 0.31),
        ("Walt Disney Company", "DIS", 0.30),
        ("Thermo Fisher Scientific", "TMO", 0.30),
        ("TJX Companies", "TJX", 0.29),
        ("Texas Instruments", "TXN", 0.29),
        ("Gilead Sciences", "GILD", 0.29),
        ("Intuitive Surgical", "ISRG", 0.29),
        ("Charles Schwab Corporation", "SCHW", 0.28),
        ("Arista Networks", "ANET", 0.28),
        ("Amphenol", "APH", 0.26),
        ("ConocoPhillips", "COP", 0.26),
        ("Pfizer", "PFE", 0.26),
        ("Boeing", "BA", 0.26),
        ("Uber", "UBER", 0.26),
        ("Deere & Company", "DE", 0.26),
        ("Analog Devices", "ADI", 0.26),
        ("AppLovin Corporation", "APP", 0.25),
        ("BlackRock", "BLK", 0.25),
        ("Lockheed Martin", "LMT", 0.25),
        ("Honeywell", "HON", 0.24),
        ("Union Pacific Corporation", "UNP", 0.24),
        ("Qualcomm", "QCOM", 0.24),
        ("Eaton Corporation", "ETN", 0.23),
        ("Booking Holdings", "BKNG", 0.23),
        ("Welltower", "WELL", 0.23),
        ("Danaher Corporation", "DHR", 0.23),
        ("Palo Alto Networks", "PANW", 0.22),
        ("Stryker Corporation", "SYK", 0.22),
        ("S&P Global", "SPGI", 0.22),
        ("Lowe's", "LOW", 0.21),
        ("Intuit", "INTU", 0.21),
        ("Chubb Limited", "CB", 0.21),
        ("Accenture", "ACN", 0.21),
        ("Progressive Corporation", "PGR", 0.20),
        ("Prologis", "PLD", 0.20),
        ("Bristol Myers Squibb", "BMY", 0.20),
        ("ServiceNow", "NOW", 0.20),
        ("Vertex Pharmaceuticals", "VRTX", 0.20),
        ("Parker Hannifin", "PH", 0.19),
        ("Capital One", "COF", 0.19),
        ("Medtronic", "MDT", 0.19),
        ("HCA Healthcare", "HCA", 0.19),
        ("CME Group", "CME", 0.19),
        ("McKesson Corporation", "MCK", 0.18),
        ("Altria", "MO", 0.18),
        ("Corning Inc.", "GLW", 0.18),
        ("Starbucks", "SBUX", 0.18),
        ("Sandisk Corporation", "SNDK", 0.18),
        ("Southern Company", "SO", 0.18),
        ("Comcast", "CMCSA", 0.18),
        ("Newmont", "NEM", 0.18),
        ("CrowdStrike", "CRWD", 0.18),
        ("Boston Scientific", "BSX", 0.18),
        ("Constellation Energy", "CEG", 0.17),
        ("Dell Technologies", "DELL", 0.17),
        ("Adobe Inc.", "ADBE", 0.17),
        ("Northrop Grumman", "NOC", 0.17),
        ("Western Digital", "WDC", 0.17),
        ("Duke Energy", "DUK", 0.17),
        ("Equinix", "EQIX", 0.16),
        ("General Dynamics", "GD", 0.16),
        ("Waste Management", "WM", 0.16),
        ("Howmet Aerospace", "HWM", 0.16),
        ("Seagate Technology", "STX", 0.16),
        ("CVS Health", "CVS", 0.15),
        ("Trane Technologies", "TT", 0.15),
        ("Intercontinental Exchange", "ICE", 0.15),
        ("Williams Companies", "WMB", 0.15),
        ("Blackstone Inc.", "BX", 0.15),
        ("Marsh & McLennan Companies", "MRSH", 0.15),
        ("Marriott International", "MAR", 0.14),
        ("FedEx", "FDX", 0.14),
        ("Automatic Data Processing", "ADP", 0.14),
        ("Quanta Services", "PWR", 0.14),
        ("American Tower", "AMT", 0.14),
        ("United Parcel Service", "UPS", 0.14),
        ("PNC Financial Services", "PNC", 0.14),
        ("Synopsys", "SNPS", 0.14),
        ("KKR", "KKR", 0.14),
        ("U.S. Bancorp", "USB", 0.14),
        ("Johnson Controls", "JCI", 0.13),
        ("BNY Mellon", "BK", 0.13),
        ("Cadence Design Systems", "CDNS", 0.13),
        ("Nike, Inc.", "NKE", 0.13),
        ("Regeneron Pharmaceuticals", "REGN", 0.13),
        ("Moody's Corporation", "MCO", 0.13),
        ("Airbnb", "ABNB", 0.13),
        ("Sherwin-Williams", "SHW", 0.13),
        ("Motorola Solutions", "MSI", 0.13),
        ("Freeport-McMoRan", "FCX", 0.13),
        ("EOG Resources", "EOG", 0.13),
        ("3M", "MMM", 0.13),
        ("Illinois Tool Works", "ITW", 0.13),
        ("Cummins", "CMI", 0.13),
        ("O'Reilly Auto Parts", "ORLY", 0.12),
        ("Kinder Morgan", "KMI", 0.12),
        ("Ecolab", "ECL", 0.12),
        ("Monster Beverage", "MNST", 0.12),
        ("Mondelez International", "MDLZ", 0.12),
        ("Emerson Electric", "EMR", 0.12),
        ("Valero Energy", "VLO", 0.12),
        ("Cintas", "CTAS", 0.12),
        ("Royal Caribbean Group", "RCL", 0.12),
        ("CSX Corporation", "CSX", 0.12),
        ("Phillips 66", "PSX", 0.12),
        ("Schlumberger", "SLB", 0.12),
        ("Aon", "AON", 0.12),
        ("Cigna", "CI", 0.12),
        ("Marathon Petroleum", "MPC", 0.12),
        ("Ross Stores", "ROST", 0.12),
        ("Colgate-Palmolive", "CL", 0.12),
        ("DoorDash", "DASH", 0.12),
        ("Warner Bros. Discovery", "WBD", 0.12),
        ("American Electric Power", "AEP", 0.12),
        ("Republic Services", "RSG", 0.11),
        ("CRH plc", "CRH", 0.11),
        ("Hilton Worldwide", "HLT", 0.11),
        ("TransDigm Group", "TDG", 0.11),
        ("L3Harris", "LHX", 0.11),
        ("General Motors", "GM", 0.11),
        ("Apollo Global Management", "APO", 0.11),
        ("Elevance Health", "ELV", 0.11),
        ("Travelers Companies", "TRV", 0.11),
        ("Robinhood Markets", "HOOD", 0.11),
        ("Cencora", "COR", 0.11),
        ("Norfolk Southern Railway", "NSC", 0.11),
        ("Air Products", "APD", 0.11),
        ("Fortinet", "FTNT", 0.10),
        ("Simon Property Group", "SPG", 0.10),
        ("Sempra", "SRE", 0.10),
        ("Occidental Petroleum", "OXY", 0.10),
        ("Baker Hughes", "BKR", 0.10),
        ("Digital Realty", "DLR", 0.10),
        ("Paccar", "PCAR", 0.10),
        ("TE Connectivity", "TEL", 0.10),
        ("Realty Income", "O", 0.10),
        ("ONEOK", "OKE", 0.10),
        ("Arthur J. Gallagher & Co.", "AJG", 0.09),
        ("Aflac", "AFL", 0.09),
        ("Truist Financial", "TFC", 0.09),
        ("Ciena Corporation", "CIEN", 0.09),
        ("AutoZone", "AZO", 0.09),
        ("Diamondback Energy", "FANG", 0.09),
        ("Allstate", "ALL", 0.09),
        ("Monolithic Power Systems", "MPWR", 0.09),
        ("Autodesk", "ADSK", 0.09),
        ("Dominion Energy", "D", 0.09),
        ("Coinbase Global", "COIN", 0.09),
        ("Corteva", "CTVA", 0.09),
        ("Target Corporation", "TGT", 0.09),
        ("Targa Resources", "TRGP", 0.09),
        ("Fastenal", "FAST", 0.09),
        ("Electronic Arts", "EA", 0.09),
        ("W. W. Grainger", "GWW", 0.08),
        ("Vistra Corp.", "VST", 0.08),
        ("Nasdaq, Inc.", "NDAQ", 0.08),
        ("Cardinal Health", "CAH", 0.08),
        ("Zoetis", "ZTS", 0.08),
        ("Carrier Global", "CARR", 0.08),
        ("NXP Semiconductors", "NXPI", 0.08),
        ("Ametek", "AME", 0.08),
        ("Edwards Lifesciences", "EW", 0.08),
        ("Xcel Energy", "XEL", 0.08),
        ("Comfort Systems USA", "FIX", 0.08),
        ("Keysight Technologies", "KEYS", 0.08),
        ("Exelon", "EXC", 0.08),
        ("Public Storage", "PSA", 0.08),
        ("Idexx Laboratories", "IDXX", 0.08),
        ("Ford Motor Company", "F", 0.08),
        ("Teradyne", "TER", 0.08),
        ("Entergy", "ETR", 0.08),
        ("Kroger", "KR", 0.08),
        ("United Rentals", "URI", 0.08),
        ("Garmin", "GRMN", 0.08),
        ("MetLife", "MET", 0.08),
        ("Datadog", "DDOG", 0.08),
        ("Becton Dickinson", "BDX", 0.07),
        ("Chipotle Mexican Grill", "CMG", 0.07),
        ("Yum! Brands", "YUM", 0.07),
        ("Hershey Company", "HSY", 0.07),
        ("Delta Air Lines", "DAL", 0.07),
        ("PayPal", "PYPL", 0.07),
        ("MSCI", "MSCI", 0.07),
        ("EQT Corporation", "EQT", 0.07),
        ("Wabtec", "WAB", 0.07),
        ("Carvana Co.", "CVNA", 0.07),
        ("Ameriprise Financial", "AMP", 0.07),
        ("Fifth Third Bancorp", "FITB", 0.07),
        ("American International Group", "AIG", 0.07),
        ("Rockwell Automation", "ROK", 0.07),
        ("Axon Enterprise", "AXON", 0.07),
        ("eBay", "EBAY", 0.07),
        ("Public Service Enterprise Group", "PEG", 0.07),
        ("Consolidated Edison", "ED", 0.07),
        ("Ventas", "VTR", 0.07),
        ("CBRE Group", "CBRE", 0.07),
        ("Sysco", "SYY", 0.07),
        ("D. R. Horton", "DHI", 0.07),
        ("Old Dominion", "ODFL", 0.07),
        ("PG&E Corporation", "PCG", 0.06),
        ("Take-Two Interactive", "TTWO", 0.06),
        ("Hartford", "HIG", 0.06),
        ("WEC Energy Group", "WEC", 0.06),
        ("Roper Technologies", "ROP", 0.06),
        ("Keurig Dr Pepper", "KDP", 0.06),
        ("Nucor", "NUE", 0.06),
        ("Crown Castle", "CCI", 0.06),
        ("Texas Pacific Land Corporation", "TPL", 0.06),
        ("Block, Inc.", "XYZ", 0.06),
        ("Las Vegas Sands", "LVS", 0.06),
        ("Live Nation Entertainment", "LYV", 0.06),
        ("Workday, Inc.", "WDAY", 0.06),
        ("Microchip Technology", "MCHP", 0.06),
        ("State Street Corporation", "STT", 0.06),
        ("Martin Marietta Materials", "MLM", 0.06),
        ("Vulcan Materials Company", "VMC", 0.06),
        ("Carnival", "CCL", 0.06),
        ("Kenvue", "KVUE", 0.06),
        ("Paychex", "PAYX", 0.06),
        ("ResMed", "RMD", 0.06),
        ("Arch Capital Group", "ACGL", 0.06),
        ("Kimberly-Clark", "KMB", 0.06),
        ("Prudential Financial", "PRU", 0.05),
        ("EMCOR Group", "EME", 0.05),
        ("Ingersoll Rand", "IR", 0.05),
        ("Archer Daniels Midland", "ADM", 0.05),
        ("GE HealthCare", "GEHC", 0.05),
        ("Copart", "CPRT", 0.05),
        ("Agilent Technologies", "A", 0.05),
        ("Estée Lauder Companies", "EL", 0.05),
        ("NRG Energy", "NRG", 0.05),
        ("Otis Worldwide", "OTIS", 0.05),
        ("Huntington Bancshares", "HBAN", 0.05),
        ("Halliburton", "HAL", 0.05),
        ("Fiserv, Inc.", "FISV", 0.05),
        ("Devon Energy", "DVN", 0.05),
        ("Atmos Energy", "ATO", 0.05),
        ("Cboe Global Markets", "CBOE", 0.05),
        ("Cognizant", "CTSH", 0.05),
        ("Iron Mountain", "IRM", 0.05),
        ("DTE Energy", "DTE", 0.05),
        ("M&T Bank", "MTB", 0.05),
        ("Waters Corporation", "WAT", 0.05),
        ("Ameren", "AEE", 0.05),
        ("Xylem Inc.", "XYL", 0.05),
        ("Interactive Brokers Group", "IBKR", 0.05),
        ("United Airlines Holdings", "UAL", 0.05),
        ("Expedia Group", "EXPE", 0.05),
        ("Hewlett Packard Enterprise", "HPE", 0.05),
        ("Vici Properties", "VICI", 0.05),
        ("Teledyne Technologies", "TDY", 0.05),
        ("Tapestry, Inc.", "TPR", 0.05),
        ("Raymond James Financial", "RJF", 0.05),
        ("Dover Corporation", "DOV", 0.05),
        ("FirstEnergy", "FE", 0.05),
        ("IQVIA", "IQV", 0.05),
        ("Verisk Analytics", "VRSK", 0.05),
        ("Willis Towers Watson", "WTW", 0.05),
        ("Extra Space Storage", "EXR", 0.05),
        ("CenterPoint Energy", "CNP", 0.05),
        ("PPL Corporation", "PPL", 0.05),
        ("Dollar General", "DG", 0.05),
        ("Edison International", "EIX", 0.05),
        ("Jabil", "JBL", 0.05),
        ("Fair Isaac", "FICO", 0.05),
        ("Biogen", "BIIB", 0.05),
        ("Charter Communications", "CHTR", 0.05),
        ("American Water Works", "AWK", 0.04),
        ("Dow Inc.", "DOW", 0.04),
        ("Constellation Brands", "STZ", 0.04),
        ("Expand Energy", "EXE", 0.04),
        ("Coterra", "CTRA", 0.04),
        ("Dexcom", "DXCM", 0.04),
        ("Rollins, Inc.", "ROL", 0.04),
        ("Fidelity National Information Services", "FIS", 0.04),
        ("Kraft Heinz", "KHC", 0.04),
        ("Hubbell Incorporated", "HUBB", 0.04),
        ("Northern Trust", "NTRS", 0.04),
        ("Eversource Energy", "ES", 0.04),
        ("Cincinnati Financial", "CINF", 0.04),
        ("W. R. Berkley Corporation", "WRB", 0.04),
        ("Mettler Toledo", "MTD", 0.04),
        ("Citizens Financial Group", "CFG", 0.04),
        ("Tractor Supply", "TSCO", 0.04),
        ("Ares Management Corporation", "ARES", 0.04),
        ("Steel Dynamics", "STLD", 0.04),
        ("LyondellBasell", "LYB", 0.04),
        ("Ulta Beauty", "ULTA", 0.04),
        ("Darden Restaurants", "DRI", 0.04),
        ("ON Semiconductor", "ON", 0.04),
        ("Omnicom Group", "OMC", 0.04),
        ("Synchrony Financial", "SYF", 0.04),
        ("Bunge Global", "BG", 0.04),
        ("Brown & Brown", "BRO", 0.04),
        ("CMS Energy", "CMS", 0.04),
        ("AvalonBay Communities", "AVB", 0.04),
        ("Qnity Electronics", "Q", 0.04),
        ("Lennar", "LEN", 0.04),
        ("Church & Dwight", "CHD", 0.04),
        ("Verisign", "VRSN", 0.04),
        ("Veralto", "VLTO", 0.04),
        ("PulteGroup", "PHM", 0.04),
        ("Regions Financial Corporation", "RF", 0.04),
        ("Equity Residential", "EQR", 0.04),
        ("Loews Corporation", "L", 0.04),
        ("PPG Industries", "PPG", 0.04),
        ("LabCorp", "LH", 0.04),
        ("Steris", "STE", 0.04),
        ("NiSource", "NI", 0.04),
        ("Quest Diagnostics", "DGX", 0.04),
        ("Equifax", "EFX", 0.04),
        ("Williams-Sonoma", "WSM", 0.04),
        ("KeyCorp", "KEY", 0.04),
        ("Leidos", "LDOS", 0.04),
        ("Dollar Tree", "DLTR", 0.04),
        ("First Solar", "FSLR", 0.04),
        ("Tyson Foods", "TSN", 0.03),
        ("Humana", "HUM", 0.03),
        ("Broadridge Financial Solutions", "BR", 0.03),
        ("Moderna", "MRNA", 0.03),
        ("C.H. Robinson", "CHRW", 0.03),
        ("Ralph Lauren Corporation", "RL", 0.03),
        ("NetApp", "NTAP", 0.03),
        ("General Mills", "GIS", 0.03),
        ("Corpay", "CPAY", 0.03),
        ("Expeditors International", "EXPD", 0.03),
        ("Southwest Airlines", "LUV", 0.03),
        ("CF Industries", "CF", 0.03),
        ("Global Payments", "GPN", 0.03),
        ("Lululemon Athletica", "LULU", 0.03),
        ("Smurfit WestRock", "SW", 0.03),
        ("J.B. Hunt", "JBHT", 0.03),
        ("T. Rowe Price", "TROW", 0.03),
        ("Snap-on", "SNA", 0.03),
        ("Albemarle Corporation", "ALB", 0.03),
        ("Principal Financial Group", "PFG", 0.03),
        ("SBA Communications", "SBAC", 0.03),
        ("Evergy", "EVRG", 0.03),
        ("Packaging Corporation of America", "PKG", 0.03),
        ("Incyte", "INCY", 0.03),
        ("CoStar Group", "CSGP", 0.03),
        ("International Paper", "IP", 0.03),
        ("PTC Inc.", "PTC", 0.03),
        ("NVR, Inc.", "NVR", 0.03),
        ("Amcor", "AMCR", 0.03),
        ("Alliant Energy", "LNT", 0.03),
        ("DuPont", "DD", 0.03),
        ("Zimmer Biomet", "ZBH", 0.03),
        ("West Pharmaceutical Services", "WST", 0.03),
        ("International Flavors & Fragrances", "IFF", 0.03),
        ("Fortive", "FTV", 0.03),
        ("Centene Corporation", "CNC", 0.03),
        ("Hologic", "HOLX", 0.03),
        ("HP Inc.", "HPQ", 0.03),
        ("Lennox International", "LII", 0.03),
        ("Weyerhaeuser", "WY", 0.03),
        ("F5, Inc.", "FFIV", 0.03),
        ("Huntington Ingalls Industries", "HII", 0.03),
        ("Akamai Technologies", "AKAM", 0.03),
        ("Insulet Corporation", "PODD", 0.03),
        ("CDW", "CDW", 0.03),
        ("Essex Property Trust", "ESS", 0.03),
        ("Textron", "TXT", 0.03),
        ("Trimble Inc.", "TRMB", 0.03),
        ("Viatris", "VTRS", 0.03),
        ("Ball Corporation", "BALL", 0.03),
        ("Jacobs Solutions", "J", 0.03),
        ("Kimco Realty", "KIM", 0.03),
        ("Tyler Technologies", "TYL", 0.03),
        ("Invitation Homes", "INVH", 0.03),
        ("TKO Group Holdings", "TKO", 0.02),
        ("Nordson Corporation", "NDSN", 0.02),
        ("Aptiv", "APTV", 0.02),
        ("McCormick & Company", "MKC", 0.02),
        ("Deckers Brands", "DECK", 0.02),
        ("Mid-America Apartment Communities", "MAA", 0.02),
        ("Pentair", "PNR", 0.02),
        ("APA Corporation", "APA", 0.02),
        ("Regency Centers", "REG", 0.02),
        ("IDEX Corporation", "IEX", 0.02),
        ("Cooper Companies", "COO", 0.02),
        ("Genuine Parts Company", "GPC", 0.02),
        ("Best Buy", "BBY", 0.02),
        ("Clorox", "CLX", 0.02),
        ("Hasbro", "HAS", 0.02),
        ("Host Hotels & Resorts", "HST", 0.02),
        ("Everest Group", "EG", 0.02),
        ("Gen Digital", "GEN", 0.02),
        ("Erie Indemnity", "ERIE", 0.02),
        ("Domino's", "DPZ", 0.02),
        ("Avery Dennison", "AVY", 0.02),
        ("Align Technology", "ALGN", 0.02),
        ("Supermicro", "SMCI", 0.02),
        ("Allegion", "ALLE", 0.02),
        ("Franklin Resources", "BEN", 0.02),
        ("Hormel Foods", "HRL", 0.02),
        ("Masco", "MAS", 0.02),
        ("Jack Henry & Associates", "JKHY", 0.02),
        ("Healthpeak Properties", "DOC", 0.02),
        ("Pinnacle West", "PNW", 0.02),
        ("Fox Corporation (Class B)", "FOX", 0.02),
        ("Generac", "GNRC", 0.02),
        ("Fox Corporation (Class A)", "FOXA", 0.02),
        ("The Trade Desk, Inc.", "TTD", 0.02),
        ("Solventum", "SOLV", 0.02),
        ("Gartner", "IT", 0.02),
        ("Universal Health Services", "UHS", 0.02),
        ("GoDaddy", "GDDY", 0.02),
        ("UDR, Inc.", "UDR", 0.02),
        ("Globe Life", "GL", 0.02),
        ("J.M. Smucker Company", "SJM", 0.02),
        ("Assurant", "AIZ", 0.02),
        ("Brown-Forman", "BF.B", 0.02),
        ("Stanley Black & Decker", "SWK", 0.02),
        ("Wynn Resorts", "WYNN", 0.02),
        ("Invesco", "IVZ", 0.02),
        ("Paramount Skydance Corp", "PSKY", 0.02),
        ("Camden Property Trust", "CPT", 0.02),
        ("AES Corporation", "AES", 0.02),
        ("Zebra Technologies", "ZBRA", 0.02),
        ("DaVita", "DVA", 0.02),
        ("Revvity", "RVTY", 0.02),
        ("MGM Resorts", "MGM", 0.02),
        ("Builders FirstSource", "BLDR", 0.02),
        ("Federal Realty Investment Trust", "FRT", 0.02),
        ("A. O. Smith", "AOS", 0.02),
        ("News Corp (Class A)", "NWSA", 0.02),
        ("Norwegian Cruise Line Holdings", "NCLH", 0.01),
        ("Baxter International", "BAX", 0.01),
        ("Henry Schein", "HSIC", 0.01),
        ("BXP, Inc.", "BXP", 0.01),
        ("Alexandria Real Estate Equities", "ARE", 0.01),
        ("Skyworks Solutions", "SWKS", 0.01),
        ("Bio-Techne", "TECH", 0.01),
        ("Molson Coors Beverage Company", "TAP", 0.01),
        ("FactSet", "FDS", 0.01),
        ("Charles River Laboratories", "CRL", 0.01),
        ("Mosaic Company", "MOS", 0.01),
        ("EPAM Systems", "EPAM", 0.01),
        ("Pool Corporation", "POOL", 0.01),
        ("Conagra Brands", "CAG", 0.01),
        ("Match Group", "MTCH", 0.01),
        ("Molina Healthcare", "MOH", 0.01),
        ("Paycom", "PAYC", 0.01),
        ("Campbell Soup Company", "CPB", 0.01),
        ("Lamb Weston", "LW", 0.01),
        ("News Corp (Class B)", "NWS", 0.01),
    ];

    public static async Task SeedAsync(AppDbContext db)
    {
        var portfolioId = AppDbContext.SpFiveHundredPortfolioId;

        // Ensure the portfolio asset itself exists
        if (!await db.Assets.AnyAsync(a => a.Id == portfolioId))
        {
            db.Assets.Add(new Asset
            {
                Id      = portfolioId,
                Name    = "S&P 500",
                Type    = AssetType.Portfolio,
                Symbol  = "SP500.PF",
                Region  = "North America",
                Country = "United States",
            });
            await db.SaveChangesAsync();
        }

        // Match component symbols to existing assets; skip any that aren't in the DB
        var allSymbols = Components.Select(c => c.Symbol).ToHashSet(StringComparer.OrdinalIgnoreCase);

        var assetIdBySymbol = (await db.Assets
            .Where(a => a.Symbol != null && allSymbols.Contains(a.Symbol) && a.Type != AssetType.Portfolio)
            .ToListAsync())
            .GroupBy(a => a.Symbol!, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                g => g.Key,
                g => g.OrderByDescending(a => a.Popularity).ThenBy(a => a.Id).First().Id,
                StringComparer.OrdinalIgnoreCase);

        // Build matched list and normalise weights so fractions sum to 1
        var matched = Components
            .Where(c => assetIdBySymbol.ContainsKey(c.Symbol))
            .ToList();

        var totalWeight = matched.Sum(c => c.Weight);

        // Upsert portfolio-asset links
        var existingRows  = await db.PortfolioAssets.Where(pa => pa.PortfolioId == portfolioId).ToListAsync();
        var existingByAssetId = existingRows.ToDictionary(pa => pa.AssetId);
        var desiredAssetIds   = matched.Select(c => assetIdBySymbol[c.Symbol]).ToHashSet();

        var toRemove = existingRows.Where(pa => !desiredAssetIds.Contains(pa.AssetId)).ToList();
        if (toRemove.Count > 0)
            db.PortfolioAssets.RemoveRange(toRemove);

        // FractionExpiry 90 days out so the snapshot weights survive daily passes
        // but refresh on the next quarterly rebalance.
        var fractionExpiry = DateTime.UtcNow.Date.AddDays(90);

        foreach (var (_, symbol, weight) in matched)
        {
            var assetId  = assetIdBySymbol[symbol];
            var fraction = weight / totalWeight;

            if (existingByAssetId.TryGetValue(assetId, out var row))
            {
                row.Fraction       = fraction;
                row.FractionExpiry = fractionExpiry;
            }
            else
            {
                db.PortfolioAssets.Add(new PortfolioAsset
                {
                    PortfolioId    = portfolioId,
                    AssetId        = assetId,
                    Quantity       = 1,
                    Fraction       = fraction,
                    FractionExpiry = fractionExpiry,
                });
            }
        }

        await db.SaveChangesAsync();
    }
}
